// <auto-generated />
namespace Assignment_5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class timeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202202200626484_timeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
